name = "Stitched"
author = "Sleepy_Evelyn"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b97c408d7a8a5f9c10e45ce8acc3309693271d2ed6034277c100dc2ee62ff17d"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
