name = "Stitched"
author = "Sleepy_Evelyn"
version = "3.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "356dac42078b1412e9527ec693e5a2ca5e8a71f648e8869b421f3f67f20d0b09"

[versions]
minecraft = "1.20.1"
quilt = "0.26.4"
